// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVzrXu4hVsC0Z8Uk8lLCPX2mCCL-aNP2o',
    appId: '1:932903787136:web:9ab45bc9081b316fb1a465',
    messagingSenderId: '932903787136',
    projectId: 'activitefirebase-5aafc',
    authDomain: 'activitefirebase-5aafc.firebaseapp.com',
    storageBucket: 'activitefirebase-5aafc.firebasestorage.app',
    measurementId: 'G-QR1M5LCH86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJEhxwPdxo1ljK7H1kE0xfxt6hcFeQyFY',
    appId: '1:932903787136:android:a01dc5f55136946fb1a465',
    messagingSenderId: '932903787136',
    projectId: 'activitefirebase-5aafc',
    storageBucket: 'activitefirebase-5aafc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVgndFtHl_bxLTIEc4JTJjM2aibCvjyUw',
    appId: '1:932903787136:ios:7f3264d2411bd33eb1a465',
    messagingSenderId: '932903787136',
    projectId: 'activitefirebase-5aafc',
    storageBucket: 'activitefirebase-5aafc.firebasestorage.app',
    iosBundleId: 'com.example.activiteFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVgndFtHl_bxLTIEc4JTJjM2aibCvjyUw',
    appId: '1:932903787136:ios:7f3264d2411bd33eb1a465',
    messagingSenderId: '932903787136',
    projectId: 'activitefirebase-5aafc',
    storageBucket: 'activitefirebase-5aafc.firebasestorage.app',
    iosBundleId: 'com.example.activiteFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVzrXu4hVsC0Z8Uk8lLCPX2mCCL-aNP2o',
    appId: '1:932903787136:web:f1979c5475e7c52ab1a465',
    messagingSenderId: '932903787136',
    projectId: 'activitefirebase-5aafc',
    authDomain: 'activitefirebase-5aafc.firebaseapp.com',
    storageBucket: 'activitefirebase-5aafc.firebasestorage.app',
    measurementId: 'G-R100MKGRQ7',
  );
}
